import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono, ADLaM_Display, Albert_Sans } from "next/font/google";
import { AgencyAuthProvider } from "@/lib/contexts/AgencyAuthContext";
import { PatientAuthProvider } from "@/lib/contexts/PatientAuthContext";
import { StaffAuthProvider } from "@/lib/contexts/StaffAuthContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const adlamDisplay = ADLaM_Display({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-adlam-display",
});

const albertSans = Albert_Sans({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-albert-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${adlamDisplay.variable} ${albertSans.variable} antialiased`}
      >
        <AgencyAuthProvider>
          <PatientAuthProvider>
            <StaffAuthProvider>
              {children}
            </StaffAuthProvider>
          </PatientAuthProvider>
        </AgencyAuthProvider>
      </body>
    </html>
  );
}
